In [64]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv(r'C:\Users\Public\python\ANACONDA\DATA SCIENCE\project with noam\project_data_3000.csv' )

In [66]:
df = pd.read_csv(r'C:\\Users\\Public\\python\\ANACONDA\\DATA SCIENCE\\project with noam\\project_data_3000.csv' )
df.drop_duplicates(subset=["Sol_Code"],inplace=True)
dup=df[(df.duplicated(subset=['User_Name']))==True]
dup_users=dup["User_Name"].unique() 
no_dup_df=pd.DataFrame(columns=df.columns)

for user_name in dup_users:
    d_df=df[df["User_Name"]==user_name]
    if(d_df.shape[0]>5):
        no_dup_df=no_dup_df.append(d_df,ignore_index=True)
        
no_dup_df

,User_Name,User_img,User_url,Challange_Name,Programming_Lang,Sol_Code,User_Score,User's_Comments,User_Gender
0,debasisdwivedy,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/debasisdwivedy,Min Window Substring,Java,import java.util.*; \nimport java.io.*;\n\ncla...,10,0,Female
1,debasisdwivedy,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/debasisdwivedy,Tree Constructor,Java,import java.util.*; \nimport java.io.*;\n\ncla...,9,0,Female
2,debasisdwivedy,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/debasisdwivedy,Bracket Matcher,Java,import java.util.*; \nimport java.io.*;\n\ncla...,10,0,Female
3,debasisdwivedy,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/debasisdwivedy,Longest Word,Java,import java.util.*; \nimport java.io.*;\n\ncla...,10,-1,Female
4,debasisdwivedy,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/debasisdwivedy,First Factorial,Java,import java.util.*; \nimport java.io.*;\n\ncla...,10,0,Female
...,...,...,...,...,...,...,...,...,...
123,samk7070,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/samk7070,Bracket Matcher,Ruby,def BracketMatcher(str)\n bracket_arr = str.s...,10,0,Female
124,samk7070,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/samk7070,Questions Marks,Ruby,def QuestionsMarks(str)\n str = str.gsub(/[a-...,10,0,NaN
125,samk7070,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/samk7070,Longest Word,Ruby,def LongestWord(sen)\n sen_arr = sen.split(' ...,10,0,NaN
126,samk7070,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/samk7070,First Factorial,Ruby,def FirstFactorial(num)\n \n idx = 1\n temp...,10,0,NaN
127,samk7070,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/samk7070,First Reverse,Ruby,def FirstReverse(str)\n\n new_str = ''\n (st...,10,0,Female

In [67]:
no_dup_df.iloc[:,0:6:5]

          User_Name                                           Sol_Code
0    debasisdwivedy  import java.util.*; \nimport java.io.*;\n\ncla...
1    debasisdwivedy  import java.util.*; \nimport java.io.*;\n\ncla...
2    debasisdwivedy  import java.util.*; \nimport java.io.*;\n\ncla...
3    debasisdwivedy  import java.util.*; \nimport java.io.*;\n\ncla...
4    debasisdwivedy  import java.util.*; \nimport java.io.*;\n\ncla...
..              ...                                                ...
123        samk7070  def BracketMatcher(str)\n  bracket_arr = str.s...
124        samk7070  def QuestionsMarks(str)\n  str = str.gsub(/[a-...
125        samk7070  def LongestWord(sen)\n  sen_arr = sen.split(' ...
126        samk7070  def FirstFactorial(num)\n  \n  idx = 1\n  temp...
127        samk7070  def FirstReverse(str)\n\n  new_str = ''\n  (st...

[128 rows x 2 columns]

In [68]:
no_dup_df.sort_values("User_Name", inplace=True)
no_dup_df

,User_Name,User_img,User_url,Challange_Name,Programming_Lang,Sol_Code,User_Score,User's_Comments,User_Gender
69,Bohdan,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/Bohdan,Questions Marks,Ruby,def QuestionsMarks(str)\n indecies = []\n ...,10,0,Male
70,Bohdan,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/Bohdan,Longest Word,Ruby,"def LongestWord(sen)\n words = sen.split("" ...",10,0,Male
71,Bohdan,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/Bohdan,First Factorial,Ruby,"def FirstFactorial(num, acc = 1)\n return a...",10,0,Male
72,Bohdan,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/Bohdan,First Reverse,Ruby,"def FirstReverse(str)\n result = """"\n id...",10,0,Male
67,Bohdan,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/Bohdan,Tree Constructor,Ruby,def TreeConstructor(strArr)\n arr = []\n s...,10,0,Male
...,...,...,...,...,...,...,...,...,...
93,tru36rit,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/tru36rit,Bracket Matcher,JavaScript,function BracketMatcher(str) {\n\tlet open = s...,10,0,Male
97,tru36rit,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/tru36rit,First Reverse,JavaScript,function FirstReverse(str) { \n // code goes ...,10,0,Female
94,tru36rit,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/tru36rit,Questions Marks,JavaScript,"function QuestionsMarks(str) {\n\t/* ""EASY"" MY...",10,0,NaN
95,tru36rit,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/tru36rit,Longest Word,JavaScript,function LongestWord(sen) {\n let result = ''...,10,0,NaN
96,tru36rit,https://s3-us-west-1.amazonaws.com/coderbytepr...,/profile/tru36rit,First Factorial,JavaScript,function FirstFactorial(num) {\n\tif (num > 0)...,10,2,Female